import { CarProps } from "@/types";

export const mockCars: CarProps[] = [
  {
    city_mpg: 25,
    class: "compact car",
    combination_mpg: 28,
    cylinders: 4,
    displacement: 1.6,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 32,
    make: "Toyota",
    model: "Corolla",
    transmission: "a",
    year: 2020,
  },
  {
    city_mpg: 22,
    class: "sedan",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2.0,
    drive: "fwd",
    fuel_type: "gas",
    highway_mpg: 30,
    make: "Honda",
    model: "Civic",
    transmission: "m",
    year: 2019,
  },
  {
    city_mpg: 20,
    class: "SUV",
    combination_mpg: 23,
    cylinders: 6,
    displacement: 3.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "Ford",
    model: "Escape",
    transmission: "a",
    year: 2021,
  },
  {
    city_mpg: 20,
    class: "SUV",
    combination_mpg: 23,
    cylinders: 6,
    displacement: 3.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "Ford",
    model: "Escape",
    transmission: "a",
    year: 2021,
  },

  {
    city_mpg: 20,
    class: "SUV",
    combination_mpg: 23,
    cylinders: 6,
    displacement: 3.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "Ford",
    model: "Escape",
    transmission: "a",
    year: 2021,
  },

  {
    city_mpg: 20,
    class: "SUV",
    combination_mpg: 23,
    cylinders: 6,
    displacement: 3.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "Ford",
    model: "Escape",
    transmission: "a",
    year: 2021,
  },
  {
    city_mpg: 20,
    class: "SUV",
    combination_mpg: 23,
    cylinders: 6,
    displacement: 3.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "Ford",
    model: "Escape",
    transmission: "a",
    year: 2021,
  },
  {
    city_mpg: 20,
    class: "SUV",
    combination_mpg: 23,
    cylinders: 6,
    displacement: 3.0,
    drive: "awd",
    fuel_type: "gas",
    highway_mpg: 28,
    make: "Ford",
    model: "Escape",
    transmission: "a",
    year: 2021,
  },
];